name: release

on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: make
        run: |
          sudo sh ./mk.sh 
      - name: one file linux
        run: |    
          cd ..
          sudo mkdir onefile
          cp -r linux-4.14.10/arch/x86_64/boot/bzimage onefile/tinycore.efi
      
      - name: upload all    
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Latest"
          prerelease: false
          title: "Development Build [单文件linux]"
          files: |
            onefile/*
            
      
